# docs: https://github.com/moulco/moul/tree/master/docs#example-moultoml
base = "/"
ga_measurement_id = ""

[style]
theme = "system-preference"
cover = "center"
content = "left"

[profile]
name = "Moul"
bio = "The minimalist publishing tool for photographers"

[social]
twitter = "moul_co"
github = "moulco/moul"
instagram = "moul.co"
facebook = ""
youtube = ""
